---
# cleanup AWS resources for Bastion VPC
- name:  delete bastion VPC and all resources
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
  - group_vars/vpc.yaml
  - group_vars/bastion.yaml
  - group_vars/docker_registry.yaml

  pre_tasks:
  # find vpc id
  - name: find vpc id
    ec2_vpc_net_facts:
      region: "{{ ec2_region }}"
      filters:
        cidr: "{{ vpc_cidr_block }}"
        tag:Name: bastion
    register: vpc_facts
    tags: [ clean ]

  roles:
    # docker registry EC2 autoscale group
    - role: docker_registry
    # bastion EC2 autoscale group
    - role: bastion_asg
    # NAT resourses
    - role: nat
    # VPC resources
    - role: vpc
