---
# Create Bastion VPC and autoscale groups
- name: Provision VPC and machines
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
  - group_vars/all.yaml
  - group_vars/envs/{{ environ | default("production") }}/vpc.yaml
  - group_vars/envs/{{ environ | default("production") }}/nat.yaml
  - group_vars/envs/{{ environ | default("production") }}/bastion.yaml
  - group_vars/envs/{{ environ | default("production") }}/docker_registry.yaml

  vars:
   - keys_link: ./keys
  pre_tasks:
   - name: collect data about ./keys
     stat: path={{keys_link}}
     register: k
   - name: fail if there is no ./keys symbolic link
     fail: msg="{{keys_link}} is not ready. Be sure you have {{keys_link}} symbolic link that points to a folder with all relevant certificates"
     failed_when: k.stat.exists!=true or k.stat.islnk!=true
   - name: set correct permissions on existing certificates (can be wrong after sync)
     command: find -L {{keys_link}} -type f -exec chmod 600 {} \;

  roles:
    # generate bastion key pair
    - role: keygen
      keypair_name: "{{ bastion_keypair_name }}"
      keypair_file: "{{ bastion_keypair_file }}"
    # generate nat key pair
    - role: keygen
      keypair_name: "{{ nat_keypair_name }}"
      keypair_file: "{{ nat_keypair_file }}"
    # generate docker-registry key pair
    - role: keygen
      keypair_name: "{{ docker_registry_keypair_name }}"
      keypair_file: "{{ docker_registry_keypair_file }}"

    # create a new VPC
    - role: vpc
    # create NAT to give internet access to instances with private IP
    - role: nat
    # create bastion EC2 autoscale group
    - role: bastion_asg
    # generate https certificates for docker registry
    - role: https_certs
    # create docker registry
    - role: docker_registry
