---
# Create Bastion VPC and autoscale groups
- name: Provision VPC and machines
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
  - group_vars/vpc.yaml
  - group_vars/bastion.yaml
  - group_vars/docker_registry.yaml

  vars:
    - keys_link: ./keys
  pre_tasks:
    - name: collect data about ./keys
      stat: path={{keys_link}}
      register: k
    - name: fail if there is no ./keys symbolic link
      fail: msg="{{keys_link}} is not ready. Be sure you have {{keys_link}} symbolic link that points to a folder with all relevant certificates"
      failed_when: k.stat.exists!=true or k.stat.islnk!=true
    - name: get all non-hiden files
      find:
        paths: "{{ k.stat.lnk_source }}"
        file_type: file
        recurse: yes
        hidden: False
      register: key_files
    - name: set correct permissions on existing certificates (can be wrong after sync)
      file:
        path: "{{ item.path }}"
        mode: 0600
      with_items: "{{ key_files.files }}"

  roles:
    # generate bastion key pair
    - role: keygen
      keypair_name: "{{ bastion_keypair_name }}"
      keypair_file: "{{ bastion_keypair_file }}"
    # generate docker-registry key pair
    - role: keygen
      keypair_name: "{{ docker_registry_keypair_name }}"
      keypair_file: "{{ docker_registry_keypair_file }}"

    # create a new VPC
    - role: vpc
      tags: [ 'vpc' ]
    # create NAT to give internet access to instances with private IP
    - role: nat
      tags: [ 'nat', 'vpc' ]
    # create bastion EC2 autoscale group
    - role: bastion_asg
      tags: [ 'bastion_asg' ]
    # generate https certificates for docker registry
    - role: https_certs
      tags: [ 'https_certs' ]
    # create docker registry
    - role: docker_registry
      tags: [ 'docker_registry' ]
