---
# delete DNS zone
- name: delete DNS zone
  route53_zone:
    vpc_id: "{{ vpc_facts.vpcs[0].id }}"
    vpc_region: "{{ ec2_region }}"
    zone: "{{ vpc_dns_zone }}"
    state: absent
  when: vpc_facts.vpcs|length > 0
  ignore_errors: true

# delete VPC
- name: delete VPC
  ec2_vpc:
    region: "{{ ec2_region }}"
    cidr_block: "{{ vpc_cidr_block }}"
    resource_tags: "{{ vpc_resource_tags }}"
    vpc_id: "{{ vpc_facts.vpcs[0].id }}"
    state: absent
    wait: true
  register: result
  when: vpc_facts.vpcs|length > 0
  until: result|success
  retries: 10
  delay: 30
  ignore_errors: true
